<?php

function admin_template_overrides_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__page-title' => [
      'template' => 'paragraph--page-title',
      'base hook' => 'paragraph'
    ],
    'paragraph__accordion' => [
      'template' => 'paragraph--accordion',
      'base hook' => 'paragraph'
    ],
    'paragraph__accordion_item' => [
      'template' => 'paragraph--accordion-item',
      'base hook' => 'paragraph'
    ],
    'paragraph__hero' => [
      'template' => 'paragraph--hero',
      'base hook' => 'paragraph'
    ],
    'paragraph__spotlight22' => [
      'template' => 'paragraph--spotlight',
      'base hook' => 'paragraph'
    ],
  ];
}

