<?php

/**
 * @file
 * Module file for the content_templates module.
 */

use Drupal\content_templates\Form\NodeDeleteForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\field\Entity\FieldConfig;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function content_templates_theme() {
  $theme = [];
  $theme['content_template'] = [
    'render element' => 'elements',
    'file' => 'content_templates.page.inc',
    'template' => 'content_template',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function content_templates_theme_suggestions_node_template(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#content_template'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'content_template__' . $sanitized_view_mode;
  $suggestions[] = 'content_template__' . $entity->bundle();
  $suggestions[] = 'content_template__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'content_template__' . $entity->id();
  $suggestions[] = 'content_template__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function content_templates_node_delete(EntityInterface $entity) {
  // Delete node templates if the source was deleted.
  $template_storage = \Drupal::entityTypeManager()->getStorage('content_template');
  $query = $template_storage->getQuery();
  $query->accessCheck(TRUE);
  $query->condition('field_source.target_id', $entity->id());
  $ids = $query->execute();
  if (!empty($ids)) {
    $content_templates = $template_storage->loadMultiple($ids);
    $template_storage->delete($content_templates);
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function content_templates_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['node'])) {
    // Set the canonical url to be not in admin.
    $entity_types['node']
      ->setFormClass('delete', NodeDeleteForm::class);
  }
}

/**
 * Implements hook_modules_installed().
 */
function content_templates_modules_installed($modules) {
  if (in_array('content_templates', $modules) && !\Drupal::service('config.installer')->isSyncing()) {
    $field_config = FieldConfig::loadByName('content_template', 'content_template', 'field_source');
    if ($field_config) {
      $bundles_to_add = [];
      $node_types = \Drupal::entityTypeManager()
        ->getStorage('node_type')
        ->loadMultiple();
      foreach ($node_types as $node_type) {
        $bundles_to_add[$node_type->id()] = $node_type->id();
      }
      if (!empty($bundles_to_add)) {
        $handler_settings = $field_config->getSetting('handler_settings');
        if (!isset($handler_settings['target_bundles'])) {
          $handler_settings['target_bundles'] = [];
        }
        $handler_settings['target_bundles'] = array_merge($handler_settings['target_bundles'], $bundles_to_add);
        // Add new allowed bundles.
        $field_config->setSetting('handler_settings', $handler_settings);
        // Save configuration.
        $field_config->save();
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function content_templates_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'quick_node_clone') !== FALSE) {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface) {
      $form_state->set('cloned_from', $node->id());
      array_unshift($form['actions']['submit']['#submit'], 'content_templates_quick_node_clone_submit');
    }
  }
}

/**
 * Submit callback for quick_node_clone forms.
 */
function content_templates_quick_node_clone_submit($form, FormStateInterface $form_state) {
  $node = $form_state->getFormObject()->getEntity();
  // Add mapping for the cloned node.
  $node->set('template', $form_state->get('cloned_from'));
}

/**
 * Implements hook_form_alter().
 */
function content_templates_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getFormObject()->getEntity();
  if (!$node->get('template')->isEmpty()) {
    // Get the mapping.
    $template = $node->get('template')->entity;
    if ($template) {
      $url = $template->toUrl('edit-form');
      $url->setOption('attributes', ['target' => '_blank']);
      $form['meta']['template'] = [
        '#type' => 'item',
        '#title' => t('Created from'),
        '#markup' => Link::fromTextAndUrl($template->label(), $url)->toString(),
        '#wrapper_attributes' => ['class' => ['entity-meta__template']],
      ];
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function content_templates_menu_local_tasks_alter(&$data, $route_name) {
  if ($route_name == 'quick_node_clone.node.quick_clone') {
    // Remove all tabs from the quick node clone form because it is confusing.
    $data['tabs'][0] = [];
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function content_templates_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'node') {
    $fields['template'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Content Template'))
      ->setDescription(t('The ID of content template entity.'))
      ->setRevisionable(FALSE)
      ->setTranslatable(FALSE)
      ->setCardinality(1)
      ->setSetting('target_type', 'node')
      ->setSetting('handler', 'default')
      ->setDisplayConfigurable('form', FALSE)
      ->setDisplayConfigurable('view', FALSE);
  }
  return $fields;
}

/**
 * Implements hook_views_data_alter().
 */
function content_templates_views_data_alter(array &$data) {
  $data['node_field_data']['template']['filter']['id'] = 'template_name';
}

/**
 * Adds content template field and filter to "Content" view.
 */
function content_templates_adjust_content_overview() {
  if (\Drupal::moduleHandler()->moduleExists('views')) {
    $view = \Drupal::entityTypeManager()->getStorage('view')->load('content');
    if ($view) {
      /** @var \Drupal\views\ViewExecutable $view_exec */
      $view_exec = \Drupal::service('views.executable')->get($view);
      $filter_settings = [
        'exposed' => TRUE,
        'expose' => [
          'label' => 'Content Template',
          'identifier' => 'template',
        ],
      ];
      $view_exec->addHandler('default', 'filter', 'node_field_data', 'template', $filter_settings, NULL);
      $field_settings = [
        'settings' => [
          'link' => TRUE,
        ],
      ];
      $view_exec->addHandler('default', 'field', 'node_field_data', 'template', $field_settings, NULL);
      $fields = $view_exec->displayHandlers->get('default')->options['fields'];
      // Re-arrange fields order.
      $template = $fields['template'];
      unset($fields['template']);
      $key = 'operations';
      $key_pos = array_search($key, array_keys($fields));
      if ($key_pos !== FALSE) {
        $second_array = array_splice($fields, $key_pos);
        $sorted_fields = array_merge($fields, ['template' => $template], $second_array);
        $view_exec->displayHandlers->get('default')->setOption('fields', $sorted_fields);
      }
      $view_exec->save();
    }
  }
}
